package com.github.lucasskywalker64.ticket.interaction.commands.admin;

import com.github.lucasskywalker64.BotMain;
import com.github.lucasskywalker64.commands.SubcommandModule;
import com.github.lucasskywalker64.ticket.TicketModule;
import com.github.lucasskywalker64.ticket.model.TicketConfig;
import com.github.lucasskywalker64.ticket.persistence.TicketRepository;
import com.github.lucasskywalker64.ticket.service.TicketConfigHolder;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.Permission;
import net.dv8tion.jda.api.entities.Guild;
import net.dv8tion.jda.api.entities.Role;
import net.dv8tion.jda.api.entities.channel.ChannelType;
import net.dv8tion.jda.api.entities.channel.concrete.Category;
import net.dv8tion.jda.api.entities.channel.concrete.TextChannel;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.interactions.commands.Command;
import net.dv8tion.jda.api.interactions.commands.OptionType;
import net.dv8tion.jda.api.interactions.commands.build.OptionData;
import net.dv8tion.jda.api.interactions.commands.build.SubcommandData;
import org.tinylog.Logger;

import java.sql.SQLException;
import java.util.EnumSet;
import java.util.List;

import static com.github.lucasskywalker64.BotConstants.INTERNAL_ERROR;

@SuppressWarnings("DataFlowIssue")
public class TicketAdminSetup implements SubcommandModule {

    private final TicketRepository repository;
    private final TicketConfigHolder configHolder;
    private final TicketModule module;

    public TicketAdminSetup() {
        repository = TicketRepository.getInstance();
        module = BotMain.getContext().ticketModule();
        this.configHolder = module.getConfigHolder();
    }

    @Override public String getRootName() { return "ticket-admin"; }
    @Override public String getSubcommandName() { return "setup"; }
    @Override public String getDescription() { return "Configure the ticket system. " +
            "Any option that isn't provided will be autogenerated."; }

    @Override public SubcommandData definition() {
        return new SubcommandData(getSubcommandName(), getDescription())
                .addOptions(
                        new OptionData(
                                OptionType.CHANNEL,
                                "category",
                                "The Discord category where the tickets should be created. Default: Tickets")
                                .setChannelTypes(ChannelType.CATEGORY),
                        new OptionData(
                                OptionType.ROLE,
                                "support-role",
                                "The role that should be pinged in a new ticket. Default: Ticket Support"),
                        new OptionData(
                                OptionType.CHANNEL,
                                "log-channel",
                                "The channel where logs should be posted to. Default: ticket-log")
                                .setChannelTypes(ChannelType.TEXT),
                        new OptionData(
                                OptionType.INTEGER,
                                "max-open-tickets-per-user",
                                "The maximum number of open tickets per user. Default: 3"),
                        new OptionData(
                                OptionType.INTEGER,
                                "auto-close-after",
                                "Auto close after x hours of inactivity. Default: 72"));
    }

    @Override
    public void handle(SlashCommandInteractionEvent event) {
        Guild guild = event.getGuild();
        event.deferReply(true).queue();

        try {
            if (repository.loadConfig() != null) {
                List<Command> commands = guild.retrieveCommands().complete();
                Command ticketAdmin = commands.stream()
                        .filter(command -> command.getName().equals("ticket-admin"))
                        .findFirst()
                        .get();
                EmbedBuilder eb = new EmbedBuilder()
                        .setTitle("Config already exists.")
                        .setDescription(String.format("If you want to change any config values please use %s",
                                String.format("</ticket-admin update:%s>", ticketAdmin.getId())));
                event.getHook().sendMessageEmbeds(eb.build()).queue();
                return;
            }
        } catch (SQLException e) {
            Logger.error(e);
            event.getHook().sendMessage(INTERNAL_ERROR).queue();
            return;
        }

        Role supportRole;
        if (event.getOption("support-role") != null) {
            supportRole = event.getOption("support-role").getAsRole();
        } else
            supportRole = guild.createRole().setName("Ticket Support").setMentionable(true).complete();

        Category category;
        if (event.getOption("category") != null) {
            category = event.getOption("category").getAsChannel().asCategory();
        } else {
            category = guild.createCategory("Tickets")
                    .addPermissionOverride(guild.getPublicRole(), null, EnumSet.of(Permission.VIEW_CHANNEL))
                    .addRolePermissionOverride(supportRole.getIdLong(),
                            EnumSet.of(
                                    Permission.VIEW_CHANNEL,
                                    Permission.MESSAGE_HISTORY,
                                    Permission.MESSAGE_SEND,
                                    Permission.MESSAGE_ATTACH_FILES), null)
                    .complete();
        }

        TextChannel logChannel;
        if (event.getOption("log-channel") != null) {
            logChannel = event.getOption("log-channel").getAsChannel().asTextChannel();
        } else
            logChannel = category.createTextChannel("ticket log").complete();

        int maxTickets;
        if (event.getOption("max-open-tickets-per-user") != null) {
            maxTickets = event.getOption("max-open-tickets-per-user").getAsInt();
        } else
            maxTickets = 3;

        int autoCloseAfter;
        if (event.getOption("auto-close-after") != null) {
            autoCloseAfter = event.getOption("auto-close-after").getAsInt();
        } else
            autoCloseAfter = 72;

        TicketConfig config = new TicketConfig(
                category.getIdLong(),
                supportRole.getIdLong(),
                logChannel.getIdLong(),
                maxTickets,
                autoCloseAfter
        );
        try {
            repository.saveConfig(config);
        } catch (SQLException e) {
            Logger.error(e);
            event.getHook().sendMessage(INTERNAL_ERROR).queue();
            if (event.getOption("support-role") == null)
                supportRole.delete().queue();
            if (event.getOption("category") == null)
                category.delete().queue();
            if (event.getOption("log-channel") == null)
                logChannel.delete().queue();
            return;
        }
        configHolder.set(config);
        module.setSetup(true);
        event.getHook().sendMessage("Ticket system configured.").queue();
    }
}
